---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      update_cache: yes

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

